apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1gdd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1gdd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1gdd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1gdd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1gdd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ygsv-tenant/rhtap-demo-app/hacbs-test-project-1gdd@sha256:e0d83c37f117c6686c7bcfc41f61f3152b32e8507a6b2417e33ee940dd554286
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
